### ISSUE TITLE
Explanation of Code

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/Hacktoberfest-Codedump#31]
Explain the code in the [folder](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/tree/main/Demonstration%20of%20Infinite%20Loop)

**Comment by YOGENDERSS** [comment]
ok will do that

**Comment by YOGENDERSS** [comment]
i have done ur work please check and make me a contributor, if possible for such more explanations. thanks
