### ISSUE TITLE
Algorithm for Fibonacci Series Printing

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/Hacktoberfest-Codedump#32]
An algorithm for the fibonacci series is required in the [folder](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/tree/main/Fibonacci)

**Comment by Rishabhraghwendra18** [comment]
Hi , @abirbhattacharya82 for which language ?

**Comment by abirbhattacharya82** [comment]
Create a Markdown file with the name "Algorithm in It"
Mention two algos
1) If using a recursive fucntion
2) If not using a recursive function
