### ISSUE TITLE
Will add a binary search

### ISSUE THREAD

**Issue by JaredsCode** [abirbhattacharya82/Hacktoberfest-Codedump#64]

**Comment by abirbhattacharya82** [comment]
- Create a Folder Named Binary Search 
- Put your code in there
- If possible add an Algorithm.md file there as well

**Comment by lucy2512** [comment]
I would like to code in C++.
Will you please assign it to me?

**Comment by abirbhattacharya82** [comment]
@lucy2512  I have assigned it to you... put in the folder named [Binary Search](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/tree/main/Binary%20Search)

**Comment by BharaniSri10** [comment]
can i add any other search?

**Comment by Lovecase** [comment]
I would like to code this for you, I can add that in C language. Can you assign me that?

**Comment by abirbhattacharya82** [comment]
@BharaniSri10 if you want to implement Binary Search then you have to do it in the language which is not yet there. Otherwise if you want to add other searching techniques then create a separate issue, I will assign it to you and create a PR respectively

**Comment by abirbhattacharya82** [comment]
@Lovecase  I have assigned it to you... put in the folder named [Binary Search](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/tree/main/Binary%20Search)

**Comment by kashish2508** [comment]
I want to code this in C++.
Will you please assign it to me?

**Comment by Lovecase** [comment]
> @Lovecase I have assigned it to you... put in the folder named [Binary Search](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/tree/main/Binary%20Search)

I have put that in folder searching methods
