### ISSUE TITLE
Will add interview problems on Dynamic Programming

### ISSUE THREAD

**Issue by Rupayan789** [abirbhattacharya82/Hacktoberfest-Codedump#79]
Please assign me this task to add problems based on knapsack

**Comment by abirbhattacharya82** [comment]
I am assigning you to this Issue. Make sure you have read the [Contributing Guidelines](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/blob/main/About/Contributing.md)

**Comment by AyushPathak12** [comment]
Please assign me some good first issue.. @abirbhattacharya82
