### ISSUE TITLE
I want to add Zig Zag Traversal in Binary Search Tree

### ISSUE THREAD

**Issue by hd2342-dubey** [abirbhattacharya82/Hacktoberfest-Codedump#81]
I want to add Zig Zag Traversal in Binary Search Tree
Please assign me this issue

**Comment by abirbhattacharya82** [comment]
go ahead and read the [Contributing](https://github.com/abirbhattacharya82/Hacktoberfest-Codedump/blob/main/About/Contributing.md) before making a PR
